# SwiftLint configuration for swift-rfc-2822
# Inherits from the shared parent configuration in swift-standards

parent_config: https://raw.githubusercontent.com/swift-standards/swift-standards/main/.swiftlint.yml

# Package-specific overrides
# RFC 2822 parsing requires complex state machines that exceed normal complexity thresholds
disabled_rules:
  - cyclomatic_complexity
  - function_body_length
